name: Korean News Clipper

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 00:00 = KST 09:00 (Daily at 9AM KST)
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send news
      env:
        SMTP_SERVER: ${{ secrets.NAVER_SERVER }}
        SMTP_PORT: ${{ secrets.NAVER_PORT }}
        SENDER_EMAIL: ${{ secrets.NAVER_USER }}
        SENDER_PASSWORD: ${{ secrets.NAVER_PASS }}
        RECIPIENT_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        echo "Workflow started at: $(date)"
        echo "UTC time: $(date -u)"
        echo "TZ environment: $TZ"
        python news_scraper.py
        echo "Workflow completed at: $(date)"